# Generated by Django 5.0.4 on 2024-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10, verbose_name='first name')),
                ('lname', models.CharField(max_length=10, verbose_name='last name')),
                ('mobile_number', models.IntegerField()),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('acoount_number', models.CharField(max_length=20)),
                ('branch_code', models.CharField(max_length=10, verbose_name='IFSC CODE')),
                ('branch_name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
